version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.2.1.2248
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=internet
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=clickhouse
    volumes:
      - ./clickhouse-init.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./data_clickhouse:/var/lib/clickhouse/
